MODULE_NAME = Chameleon
MODULE_AUTHOR = Chameleon
MODULE_DESCRIPTION = This module enables the HPET is not done so by the bios
MODULE_VERSION = "1.0.0"
MODULE_COMPAT_VERSION = "1.0.0"
MODULE_START = $(MODULE_NAME)_start
MODULE_DEPENDENCIES =

DIR = ${MODULE_NAME}

MODULE_OBJS = module.x86.mach.o

include ../MakeInc.dir
