MODULE_NAME = GUI
MODULE_AUTHOR = Chameleon
MODULE_DESCRIPTION = This module provides for a GUI
MODULE_VERSION = "1.0.0"
MODULE_COMPAT_VERSION = "1.0.0"
MODULE_START = $(MODULE_NAME)_start
MODULE_DEPENDENCIES =

DIR = ${MODULE_NAME}

MODULE_OBJS = module.x86.mach.o gui.x86.mach.o picopng.x86.mach.o graphics.x86.mach.o graphic_utils.x86.mach.o

include ../MakeInc.dir
