MODULE_NAME = USBFix
MODULE_AUTHOR = Chameleon
MODULE_DESCRIPTION = This module provides for usb fixup support
MODULE_VERSION = "1.0.0"
MODULE_COMPAT_VERSION = "1.0.0"
MODULE_START = $(MODULE_NAME)_start
MODULE_DEPENDENCIES =

DIR = ${MODULE_NAME}

MODULE_OBJS = module.x86.mach.o usb.x86.mach.o

include ../MakeInc.dir
