MODULE_NAME = ACPICodec
MODULE_DESCRIPTION = This module provides a remplacement for the internal acpi patcher
MODULE_AUTHOR = "Cparm"
MODULE_VERSION = "1.0.0"
MODULE_COMPAT_VERSION = "1.0.0"
MODULE_START = $(MODULE_NAME)_start
MODULE_DEPENDENCIES = Chameleon

DIR = AcpiCodec

MODULE_OBJS = ACPICodec.x86.mach.o acpi_tools.x86.mach.o acpi_codec.x86.mach.o acpidecode.x86.mach.o acpicode.x86.mach.o 

include ../MakeInc.dir
