MODULE_NAME = GraphicsEnabler
MODULE_AUTHOR = Chameleon
MODULE_DESCRIPTION = This module provides for AMD, Intel And Nvidia graphics injection
MODULE_VERSION = "1.0.0"
MODULE_COMPAT_VERSION = "1.0.0"
MODULE_START = $(MODULE_NAME)_start
MODULE_DEPENDENCIES =

DIR = ${MODULE_NAME}

MODULE_OBJS = ati.x86.mach.o gma.x86.mach.o nvidia.x86.mach.o nvidia_helper.x86.mach.o enabler.x86.mach.o

include ../MakeInc.dir
