SRCROOT = $(abspath $(CURDIR)/../../..)
OBJROOT = $(SRCROOT)/obj/i386/modules/$(DIR)
SYMROOT = $(SRCROOT)/sym/i386
DSTROOT = $(SRCROOT)/dst/i386
DOCROOT = $(SRCROOT)/doc
IMGROOT = $(SRCROOT)/sym/cache
IMGSKELROOT = $(SRCROOT)/imgskel
CDBOOT = ${IMGROOT}/usr/standalone/i386/cdboot

BOOT_ELF = ${SYMROOT}/boot.elf

include ${SRCROOT}/Make.rules


CFLAGS := $(CLFAGS) -nostdinc -Werror \
	-fno-builtin -fno-stack-protector \
	-march=pentium4 -msse2 -msoft-float \
	-include $(SRCROOT)/autoconf.h

CPPFLAGS := $(CPPFLAGS) -nostdinc -Werror \
	-fno-builtin -fno-stack-protector \
	-march=pentium4 -msse2 -msoft-float \
	-include $(SRCROOT)/autoconf.h

UTILDIR = ${SRCROOT}/i386/util
LIBSADIR = ${SRCROOT}/i386/libsa
LIBSAIODIR = ${SRCROOT}/i386/libsaio
BOOT2DIR = ${SRCROOT}/i386/boot2

MODULE_INCLUDES :=  $(foreach x,$(MODULE_DEPENDENCIES),-I$(SRCROOT)/i386/modules/$(x)/include/)


INC = -I$(SRCROOT)/i386/modules/include/ -Iinclude/ -I$(SRCROOT)/i386/libsaio/ -I$(SRCROOT)/i386/libsa/ -I$(SRCROOT)/i386/include/ -I$(SRCROOT)/i386/boot2/ $(MODULE_INCLUDES)
DEFINES := -D__KLIBC__ $(DEFINES)

MODULE_DEPENDENCIES :=  $(wildcard $(foreach x,$(MODULE_DEPENDENCIES),$(SYMROOT)/modules/$(x).dylib)) \
						$(wildcard $(foreach x,$(MODULE_DEPENDENCIES),$(OBJROOT)/../$(x).dylib))

MODULE_DEPENDENCIES_CMD := $(foreach x,$(MODULE_DEPENDENCIES), -weak_library $(x))

INSTALLDIR = $(DSTROOT)/System/Library/Frameworks/System.framework/Versions/B/PrivateHeaders/standalone

MODULE_DEFINITION := $(CONFIG_$(shell echo $(MODULE_NAME) | tr '[:lower:]' '[:upper:]')_MODULE)


ifeq  ($(MODULE_DEFINITION),m)
ifneq ($(BUILT_IN),yes)

# Make this as a *MODULE*
all: $(CONFIG_HEADERS) $(HEADER_VERSION) dylib all-recursive

else
# Module not selected to be compiled as a module
all: $(CONFIG_HEADERS) $(HEADER_VERSION) all-recursive

endif

else

# Don't compile this module
all:

endif


dylib_LINKER: $(SYMROOT)/boot_modules.c $(SYMROOT)/boot_modules.h dylib 

dylib: ${SYMROOT}/modules/ ${OBJROOT} $(SYMROOT)/modules/$(MODULE_NAME).dylib

MODULE_OBJS := $(addprefix $(OBJROOT)/, ${MODULE_OBJS})

$(SYMROOT)/modules/$(MODULE_NAME).dylib: $(MODULE_OBJS) $(MODULE_DEPENDENCIES) $(OBJROOT)/$(MODULE_NAME).desc $(OBJROOT)/$(MODULE_NAME).author ${BOOT_ELF} Makefile
	@echo "	[LD] $(MODULE_NAME).dylib"
	@#$(X86_MACH_CC) $(LDFLAGS) -m mach_i386 -shared $(INC) -o $@ ${filter %.o %.a, $^}
	@/opt/xZenue/bin/i386-apple-darwin10-ld -arch i386 -undefined dynamic_lookup \
		    -dylib -read_only_relocs suppress \
		    -alias _$(MODULE_START) start \
		    -S -Z -dead_strip_dylibs \
		    -no_uuid \
		    -current_version $(MODULE_VERSION) -compatibility_version $(MODULE_COMPAT_VERSION) \
		    -final_output $(MODULE_NAME) \
		    $(filter %.o,$^) \
		    -macosx_version_min 10.6 \
		    -sectcreate __INFO __author $(OBJROOT)/$(MODULE_NAME).author \
		    -sectcreate __INFO __description $(OBJROOT)/$(MODULE_NAME).desc \
		    -o $(SYMROOT)/modules/$(MODULE_NAME).dylib

clean-local:
	@if [ -f "$(SYMROOT)/modules/$(MODULE_NAME).dylib" ];then \
        echo "	[RM] $(SYMROOT)/modules/$(MODULE_NAME).dylib";\
    fi
	@for o in $(MODULE_OBJS); do if [ -f "$${o}" ];then echo "	[RM] $${o}"; fi; done
	@rm -f $(SYMROOT)/modules/$(MODULE_NAME).dylib
	@rm -rf $(OBJROOT)


${SYMROOT}/modules/:
	@echo "	[MKDIR] $@"
	@$(MKDIRS) $@

.PHONY: $(SYMROOT)/boot_modules.h
.PHONY: $(SYMROOT)/boot_modules.c

$(SYMROOT)/boot_modules.c: 
	@echo "	start_built_in_module(\"$(MODULE_NAME)\", \"$(MODULE_AUTHOR)\", \"$(MODULE_DESCRIPTION)\", 0, 0, &$(MODULE_START));" >> $@

$(SYMROOT)/boot_modules.h:
	@echo "void $(MODULE_START)(); // $(MODULE_NAME)" >> $@

$(OBJROOT)/$(MODULE_NAME).author: Makefile
	@echo "$(MODULE_AUTHOR)" > $@

$(OBJROOT)/$(MODULE_NAME).desc: Makefile
	@echo "$(MODULE_DESCRIPTION)" > $@

#dependencies
-include $(OBJROOT)/Makedep
