MODULE_NAME = MemoryInfo
MODULE_AUTHOR = Chameleon
MODULE_DESCRIPTION = This module provides for SPD ram detection
MODULE_VERSION = "1.0.0"
MODULE_COMPAT_VERSION = "1.0.0"
MODULE_START = $(MODULE_NAME)_start
MODULE_DEPENDENCIES = Chameleon

DIR = ${MODULE_NAME}

MODULE_OBJS = module.x86.mach.o spd.x86.mach.o dram_controllers.x86.mach.o

include ../MakeInc.dir
